# Generated by Django 4.1.3 on 2022-12-19 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='status',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='course_video.status'),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Yet to Start', 'Yet to Start'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
