# Generated by Django 4.1.3 on 2022-12-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.URLField(),
        ),
    ]
