# Generated by Django 4.1.3 on 2023-01-16 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course_video", "0002_remove_playlistitem_playlist_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="favourites",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="favourite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
