# Generated by Django 4.1.3 on 2022-12-20 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0003_remove_playlistitem_status_alter_status_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistitem',
            name='status',
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_video.status'),
        ),
    ]
