# Generated by Django 4.1.3 on 2023-01-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_video", "0003_profile_facebook_url_profile_instagram_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="instagram_url",
        ),
        migrations.AddField(
            model_name="profile",
            name="time_left",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
