# Generated by Django 4.1.3 on 2023-01-16 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course_video", "0003_course_favourites"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="watch_later",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="watch_later",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
