# Generated by Django 4.1.3 on 2023-01-16 08:45
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course_video", "0004_course_watch_later"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistitem",
            name="watch_later_playlist",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="watch_later_playlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
