# Generated by Django 4.1.3 on 2022-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0004_alter_course_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
