# Generated by Django 4.1.3 on 2023-01-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_video", "0004_remove_profile_instagram_url_profile_time_left"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="playlist_title",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course_video.course",
            ),
        ),
    ]
