# Generated by Django 4.1.3 on 2022-12-20 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0005_status_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_video.status'),
        ),
    ]
