# Generated by Django 4.1.3 on 2023-01-08 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_video", "0005_profile_playlist_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="playlist_title",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_left",
                to="course_video.course",
            ),
        ),
    ]
