# Generated by Django 4.1.3 on 2023-01-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_video", "0006_alter_profile_playlist_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="time_left",
            field=models.TimeField(),
        ),
    ]
