# Generated by Django 4.1.3 on 2022-12-20 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_video', '0006_alter_playlistitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='author',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='status',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
