# Generated by Django 4.1.3 on 2023-01-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_video", "0008_remove_profile_time_left"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="playlist_title",
        ),
    ]
