# Generated by Django 4.1.3 on 2022-12-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0008_course_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': (('can_add_cource', 'Can add course'), ('can_view_cource', 'Can view course'))},
        ),
    ]
