# Generated by Django 4.1.3 on 2022-12-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0008_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
