# Generated by Django 4.1.3 on 2023-01-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_video", "0009_remove_profile_playlist_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="time_preference",
            field=models.CharField(
                choices=[("H", "Hours"), ("M", "Minutes"), ("S", "Seconds")],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
