# Generated by Django 4.1.3 on 2022-12-20 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_video', '0009_alter_playlistitem_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
