# Generated by Django 4.1.3 on 2022-12-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0009_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AddField(
            model_name='course',
            name='public',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
