# Generated by Django 4.1.3 on 2022-12-20 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_video', '0010_alter_playlistitem_author_alter_playlistitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='author',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
