# Generated by Django 4.1.3 on 2022-12-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0011_alter_playlistitem_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='link',
            field=models.URLField(blank='true'),
        ),
    ]
