# Generated by Django 4.1.3 on 2022-12-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0012_playlistitem_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='list_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='course_video.course'),
        ),
    ]
