# Generated by Django 4.1.3 on 2022-12-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0015_remove_playlistitem_id_alter_playlistitem_list_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='list_item',
            field=models.CharField(max_length=150),
        ),
    ]
