# Generated by Django 4.1.3 on 2022-12-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0016_playlistitem_id_alter_playlistitem_list_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='list_item',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='course_video.course'),
        ),
    ]
