# Generated by Django 4.1.3 on 2022-12-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0017_alter_playlistitem_list_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='list_item',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
