# Generated by Django 4.1.3 on 2022-12-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0018_alter_playlistitem_list_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
